### ISSUE TITLE
Informacja o możliwości kontrybucji

### ISSUE THREAD

**Issue by darkowic** [RacyMind/kalkulator-dla-przedsiebiorcy-vue#76]
Na stronie powinna znaleźć się wyraźna informacja, że kod jest dostępny na githubie i można kontrybuować.

**Comment by RacyMind** [comment]
Dodałem w menu link do GitHuba. Programista zrozumie :)

**Comment by darkowic** [comment]
Przez issue https://github.com/RacyMind/kalkulator-dla-przedsiebiorcy-vue/issues/78 tego nie widziałem. Dzięki!

**Comment by RacyMind** [comment]
Tak mam spory problem z tym issue. Musi zostać jak najszybciej poprawiony :/
